apiVersion: v1
kind: Service
metadata:
  labels:
    app: fun-platform-lms
  name: lms  # name of the service should be host name in nginx
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    deploymentconfig: fun-platform-lms
  type: ClusterIP
