apiVersion: v1
kind: Service
metadata:
  labels:
    app: fun-platform-memcached
  name: memcached  # name of the service should be host name in nginx
spec:
  ports:
  - name: 11211-tcp
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    deploymentconfig: fun-platform-memcached
  type: ClusterIP
