apiVersion: v1
kind: Service
metadata:
  labels:
    app: fun-platform-mongodb
  # name of the service should be mongodb host name in settings
  name: mongodb
spec:
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: fun-platform-mongodb
  # name of the endpoint should be the same as the above service
  name: mongodb
subsets:
  - addresses:
    - ip: 192.168.10.11
    ports:
    - port: 27017
      name: 27017-tcp
