apiVersion: v1
kind: Service
metadata:
  labels:
    app: fun-platform-mysql
  # name of the service should be database host name in settings
  name: mysql
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: fun-platform-mysql
  # name of the endpoint should be the same as the above service
  name: mysql
subsets:
  - addresses:
    - ip: 192.168.10.254
    ports:
    - port: 3306
      name: 3306-tcp
