apiVersion: v1
kind: Route
metadata:
  labels:
    app: fun-platform-cms
  name: cms
spec:
  host: campus-dev-cms.dev.fun-mooc.fr
  port:
    targetPort: 8081-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: nginx
    weight: 100
